### ISSUE TITLE
How to show long contents

### ISSUE THREAD

**Issue by Poldan** [anseki/jquery-plainmodal#10]
- Real need option to disable closing modal by click on modal overlay

- Content with big height vot visible in this modal.

**Comment by anseki** [comment]
Hi @Poldan, thank you for the comment.

- The first one, [`plainmodalbeforeclose`](https://github.com/anseki/jquery-plainmodal#plainmodalbeforeclose) event may help you.  
See: https://github.com/anseki/jquery-plainmodal/issues/3, https://github.com/anseki/jquery-plainmodal/issues/9
- The second one, more details please.

**Comment by Poldan** [comment]
Hi @anseki 
Window screen has height 600px. Modal content has height 900px.
How to show hidden contents?

**Comment by anseki** [comment]
Typically, a long content is shown by scrolling frame such as `overflow: scroll`/`overflow: auto`.

**Comment by Poldan** [comment]
http://getbootstrap.com/javascript/#modals
Can i do something, like bt modal with your plugin?
If modal block will be inside wrapper(now his place near wrap), then i can do:
1) wrapper is fixed, overflow:auto
2) modal is absolute, and we have scroll on the right side of the screen

p.s. sorry, my english is so bad

**Comment by anseki** [comment]
Do you want the Bootstrap style?
Or, do you want to make a scrollable element?

For example, implement both:

https://jsfiddle.net/L0cug7vn/show/ (Click "Open Modal" button)

- See http://anseki.github.io/jquery-plainmodal/ for the style.
- See the `.modal-body` class in the example for the scrollable element.

**Comment by anseki** [comment]
BTW, was the first question (disabling closing the modal window) in [your comment](https://github.com/anseki/jquery-plainmodal/issues/10#issue-201185643) already solved?
I change the title of this issue. Please make a new issue if you want. You should make one issue by one topic because this is issue tracker system.

**Comment by Poldan** [comment]
I have added new option : {'closeOnModal':boolean}, and, when it's true, don't create click events on modal window. 
Scrollbar inside window is working, but creating some bad thing (max-height must be setted).
But if it works, i can use it :+1: 
Thanks for answersm @anseki

**Comment by anseki** [comment]
The `closeOnModal` option is unnecessary because those events are cancelable.
A scrollable element and its style like `max-height` are unrelated to the jQuery-plainModal. It is CSS style specification.
You can learn at here: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
The jQuery-plainModal should do nothing about the style.

Anyway the issues were solved? I close this issue.
