### ISSUE TITLE
Add closing options

### ISSUE THREAD

**Issue by luansemensatoribeiro** [anseki/jquery-plainmodal#3]
- Disable closing by esc key
- Disable closing by clicking outside the modal

**Comment by anseki** [comment]
Hi luansemensatoribeiro, Thank you for your post.
Do you want to make the modal stay opening when those events are fired?
Does the `plainmodalbeforeclose` event help you?
```js
$('#modal').on('plainmodalbeforeclose', function(e) { e.preventDefault(); });
```
https://github.com/anseki/jquery-plainmodal#plainmodalbeforeclose

**Comment by luansemensatoribeiro** [comment]
Hi @anseki.
With the modal already open, I need to block the closure from the esc key, and clicking outside the content (black overlay).
Will only be possible through the close button (`$. closeOverlay ();`).

**Comment by anseki** [comment]
Yes, of course those you needed are granted.
If the `plainmodalbeforeclose` has a problem, please tell me it.
[Before](https://github.com/anseki/jquery-plainmodal/commit/a8826b3229b6a0e06049927dbb2f985c8e139482), I didn't add those options, and I added those events that is useful and free customizable, because the programers who use plainModal should be able to decide what is disabled or not.
Then, you can customize the behavior freely like #2.

**Comment by anseki** [comment]
There is no reply, and 8 days have passed.
I think that this problem was already solved, and I close the issue.
If not solved, please reopen it.
