### ISSUE TITLE
Scroll of modal window doesn't work on iPhone 5

### ISSUE THREAD

**Issue by cisfor** [anseki/jquery-plainmodal#7]
Hello,

Thank you so much for your jquery code. I'm using it on a new website and everything works perfectly on the desktop version. But when I try to view it on my iPhone 5, I cannot scroll down in the modal window to view the complete text.

The website is: www.mannkraft.eu/preview and the button is "HOW IT ALL BEGAN".

Thanks for any help regarding this issue,
Clinton

**Comment by anseki** [comment]
Hi @cisfor, thank you for your post.

Unfortunately, some web browsers have bug.
Firefox for mobile especially can't control scrolling a page. Then plainModal disables touch-event of modal window to avoid scroll.

By the way, since a modal window is usually used to show message such as confirmation, it might be unfit to show long content. (especially, small screen)
Or, using paging that switches a view instead of scrolling may help you.

**Comment by cisfor** [comment]
Hi - thanks for your answer. I actually just changed the javascript file at lines 61 and 94 to "true" (the lines which programme to "avoid scroll on touch devices") and now it scrolls perfectly :)

**Comment by anseki** [comment]
By reason I said, that customized script may not work in many mobile browsers.
Another way: https://jsfiddle.net/c8w0Lgdw/
This will work in mobile browsers also. Scrolling and modal window.

**Comment by anseki** [comment]
The sample above uses this:
http://anseki.github.io/overflow-android/
Of course, this works in other than Android also.

**Comment by anseki** [comment]
No reply came, and I close this issue.
